// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Title$TetrisRescript from "../Title/Title.bs.js";
import * as GameInfo$TetrisRescript from "../GameInfo/GameInfo.bs.js";
import * as StoreContext$TetrisRescript from "../../store/StoreContext.bs.js";
import * as GameGlassView$TetrisRescript from "../GameGlassView/GameGlassView.bs.js";
import * as GameController$TetrisRescript from "../../store/GameController.bs.js";

var rootStyle = {
  backgroundColor: "#111",
  color: "#eee",
  display: "flex",
  height: "100vh",
  overflow: "hidden",
  width: "100vw",
  alignItems: "center",
  flexDirection: "column"
};

var twoColumnContainerStyle = {
  display: "flex"
};

var leftColumnStyle = {
  width: "25vw"
};

function App(Props) {
  return React.createElement(StoreContext$TetrisRescript.make, {
              children: React.createElement("div", {
                    style: rootStyle
                  }, React.createElement(GameController$TetrisRescript.make, {}), React.createElement(Title$TetrisRescript.make, {}), React.createElement("div", {
                        style: twoColumnContainerStyle
                      }, React.createElement("div", {
                            style: leftColumnStyle
                          }, React.createElement(GameInfo$TetrisRescript.make, {})), React.createElement("div", undefined, React.createElement(GameGlassView$TetrisRescript.make, {}))))
            });
}

var make = App;

export {
  rootStyle ,
  twoColumnContainerStyle ,
  leftColumnStyle ,
  make ,
  
}
/* react Not a pure module */
