// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

var style = {
  background: "transparent",
  border: "2px solid green",
  color: "green",
  cursor: "pointer",
  fontSize: "1.5rem",
  padding: "1rem 2rem"
};

function Button(Props) {
  var children = Props.children;
  var onClick = Props.onClick;
  return React.createElement("button", {
              style: style,
              onClick: (function (param) {
                  return Curry._1(onClick, undefined);
                })
            }, children);
}

var make = Button;

export {
  style ,
  make ,
  
}
/* react Not a pure module */
