// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Constants$TetrisRescript from "../../constants/Constants.bs.js";

function getStyle(color) {
  return {
          backgroundColor: color,
          height: "30px",
          marginRight: "3px",
          marginBottom: "3px",
          width: "30px"
        };
}

function GlassCell(Props) {
  var cell = Props.cell;
  if (cell) {
    return React.createElement("div", {
                style: getStyle(Constants$TetrisRescript.getColorString(cell._0))
              });
  } else {
    return React.createElement("div", {
                style: getStyle(Constants$TetrisRescript.getColorString(/* Grey */0))
              });
  }
}

var make = GlassCell;

export {
  getStyle ,
  make ,
  
}
/* react Not a pure module */
