// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Store$TetrisRescript from "./Store.bs.js";

var initialState = Store$TetrisRescript.getInitialState(undefined);

var context = React.createContext({
      state: initialState,
      dispatch: (function (param) {
          
        })
    });

function StoreContext(Props) {
  var children = Props.children;
  var provider = context.Provider;
  var match = React.useReducer(Store$TetrisRescript.reducer, initialState);
  return React.createElement(provider, {
              children: children,
              value: {
                state: match[0],
                dispatch: match[1]
              }
            });
}

var make = StoreContext;

export {
  initialState ,
  context ,
  make ,
  
}
/* initialState Not a pure module */
