// Generated by ReScript, PLEASE EDIT WITH CARE


function getColorString(color) {
  switch (color) {
    case /* Grey */0 :
        return "#333";
    case /* Red */1 :
        return "#b33";
    case /* Green */2 :
        return "#3b3";
    case /* Blue */3 :
        return "#33b";
    case /* Yellow */4 :
        return "#bb3";
    case /* Cyan */5 :
        return "#3bb";
    case /* Magenta */6 :
        return "#b3b";
    case /* Orange */7 :
        return "#b83";
    
  }
}

var startPosition = [
  4,
  1
];

var leftOffset = [
  -1,
  0
];

var rightOffset = [
  1,
  0
];

var downOffset = [
  0,
  1
];

export {
  getColorString ,
  startPosition ,
  leftOffset ,
  rightOffset ,
  downOffset ,
  
}
/* No side effect */
