// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Text$TetrisRescript from "../Common/Text.bs.js";

function Title(Props) {
  return React.createElement(Text$TetrisRescript.make, {
              children: "TETRIS",
              size: /* Title */0
            });
}

var make = Title;

export {
  make ,
  
}
/* react Not a pure module */
