// Generated by ReScript, PLEASE EDIT WITH CARE


function isEmpty(cell) {
  if (cell) {
    return false;
  } else {
    return true;
  }
}

function empty(param) {
  return /* Empty */0;
}

export {
  isEmpty ,
  empty ,
  
}
/* No side effect */
