// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as CoreLogic$TetrisRescript from "../../core/CoreLogic.bs.js";
import * as GlassGrid$TetrisRescript from "../Common/GlassGrid.bs.js";
import * as StoreContext$TetrisRescript from "../../store/StoreContext.bs.js";
import * as GameGlassContainer$TetrisRescript from "./GameGlassContainer.bs.js";

function GameGlassView(Props) {
  var match = React.useContext(StoreContext$TetrisRescript.context);
  var state = match.state;
  var match$1 = state.mode;
  var glass = Curry._1(CoreLogic$TetrisRescript.GameGlass.toArray, match$1 !== 1 ? state.glass : CoreLogic$TetrisRescript.mergeFigure(state.glass, state.currentFigure, state.currentPosition));
  return React.createElement(GameGlassContainer$TetrisRescript.make, {
              children: React.createElement(GlassGrid$TetrisRescript.make, {
                    glass: glass
                  })
            });
}

var make = GameGlassView;

export {
  make ,
  
}
/* react Not a pure module */
