// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var containerStyle = {
  border: "4px solid gray",
  borderTop: "none",
  paddingTop: "4px",
  paddingLeft: "4px"
};

function GameGlassContainer(Props) {
  var children = Props.children;
  return React.createElement("div", {
              style: containerStyle
            }, children);
}

var make = GameGlassContainer;

export {
  containerStyle ,
  make ,
  
}
/* react Not a pure module */
